/**
 * Parameter copy shown in the training and preset editors.
 * FIELD_HINTS: one short line under every non-switch field.
 * FIELD_HELP: the detailed text behind the help button, where the schema text is too terse.
 */
type Copy = [string, string];

export const FIELD_HINTS: Record<string, Copy> = {
  'model.family': ['选择要训练的模型，B 表示十亿参数。', 'The model to train; B means billion parameters.'],
  'training.mode': ['LoRA／LoKr 训练附加权重；全量微调直接更新模型。', 'LoRA / LoKr trains added weights; full fine-tuning updates the model.'],
  'training.resume_weights': ['从导出的全量模型继续微调，留空从底模开始。', 'Continue from an exported full model; blank starts from the base.'],
  'model.tokenizer_path': ['留空自动使用模型目录或内置分词器。', 'Blank uses the model folder or built-in tokenizers.'],
  'model.prediction_type': ['须与模型一致，常规 SDXL 选 ε 预测。', 'Must match the model; standard SDXL uses epsilon.'],
  'model.sdxl_max_token_length': ['标签最多编码的长度，超出部分截断。', 'Longest caption encoded; the rest is truncated.'],
  'model.flux2_variant': ['Klein 基础版的规模，完整目录可自动识别。', 'Klein base size; full folders are detected automatically.'],
  'model.krea2_variant': ['未登记的文件需确认是 Raw 还是 Turbo。', 'Confirm Raw or Turbo for unregistered files.'],
  'model.attention': ['注意力的计算方式，影响速度和显存。', 'How attention is computed; affects speed and memory.'],

  'dataset.sources': ['每个目录可单独设置重复次数和用途。', 'Each folder has its own repeats and purpose.'],
  'dataset.resolution_mode': ['分桶统一训练面积；原生保留每张图的尺寸。', 'Buckets share one area; native keeps each image size.'],
  'dataset.resolutions': ['每个分桶的基准边长，多个用逗号分隔。', 'Base side per bucket; separate several with commas.'],
  'dataset.image_fit': ['图片与训练尺寸比例不同时补边或裁切。', 'Pad or crop when the image and training shape differ.'],
  'dataset.native_max_pixels': ['单张图片允许的最大面积。', 'Largest area allowed for one image.'],
  'dataset.native_max_side': ['宽或高超过此值时等比缩小。', 'Wider or taller images are scaled down.'],
  'dataset.native_overflow': ['图片超出尺寸上限时的处理方式。', 'What happens when an image exceeds the limits.'],
  'dataset.aspect_ratio_limit': ['分桶最宽的比例，2 表示最宽 2:1。', 'Widest bucket shape; 2 means up to 2:1.'],
  'dataset.area_tolerance': ['分桶面积可偏离基准面积的比例。', 'How far a bucket area may differ from the base.'],
  'dataset.bucket_step': ['分桶宽高的间隔，留空通常为 64。', 'Spacing between bucket sizes; blank is usually 64.'],
  'dataset.batch_size': ['每张显卡一次处理的图片数。', 'Images each GPU processes at once.'],
  'dataset.text_encoding': ['标签的编码方式，缓存可节省显存。', 'How captions are encoded; caching saves memory.'],
  'dataset.num_workers': ['后台读取图片的进程数，Windows 建议 0。', 'Background loaders; use 0 on Windows.'],
  'dataset.cache_dir': ['图像与文本缓存的位置，留空放在输出目录。', 'Where caches are kept; blank uses the output folder.'],

  'dataset.caption.trigger_word': ['放在标签开头，不参与打乱和丢弃。', 'Placed first; never shuffled or dropped.'],
  'dataset.caption.prefix': ['加在每条标签最前面的固定文字。', 'Fixed text before every caption.'],
  'dataset.caption.suffix': ['加在每条标签末尾的固定文字。', 'Fixed text after every caption.'],
  'dataset.caption.separator': ['拆分 TXT 标签的字符，默认为逗号。', 'Character that splits TXT tags; comma by default.'],
  'dataset.caption.keep_tokens': ['开头几个标签位置固定，不被打乱或丢弃。', 'Leading tags stay in place and are never dropped.'],
  'dataset.caption.tag_dropout': ['每个标签被随机去掉的概率。', 'Chance to drop each tag.'],
  'dataset.caption.caption_dropout': ['整条标签被置空的概率，有助于 CFG。', 'Chance to blank the whole caption; helps CFG.'],
  'dataset.caption.cache_variants': ['缓存文本时每张图预生成的随机组合数。', 'Random caption variants cached per image.'],

  'loop.gpu_count': ['1 为单卡；多卡可选择数据并行或显存分片。', '1 uses one GPU; several can split data or memory.'],
  'loop.distributed_strategy': ['数据并行分配训练数据；显存分片把模型分到多卡。', 'Data parallel splits data; sharding splits the model.'],
  'loop.grad_accum': ['累积几个批次再更新一次参数。', 'Batches accumulated before each update.'],
  'loop.epochs': ['完整遍历全部训练图片的次数。', 'Passes over the whole training set.'],
  'loop.max_steps': ['最多更新多少次，留空按轮数结束。', 'Most updates to run; blank stops by epochs.'],
  'loop.mixed_precision': ['训练运算使用的精度，BF16 最常用。', 'Precision used for training math; BF16 is typical.'],
  'loop.seed': ['固定后可重现相同的数据顺序和噪声。', 'Fixes data order and noise for repeatable runs.'],
  'loop.ema_decay': ['越接近 1，平均权重变化越慢。', 'Closer to 1 averages more slowly.'],
  'loop.nan_skip_limit': ['连续出现无效数值时最多跳过的步数。', 'Invalid steps skipped in a row before stopping.'],
  'loop.log_every': ['每隔多少步记录一次训练指标。', 'Record metrics every N steps.'],

  'adapter.algo': ['附加权重的结构，LoRA 最常用。', 'Structure of the added weights; LoRA is most common.'],
  'adapter.preset': ['选择 LoRA／LoKr 作用的模型层。', 'Which layers receive adapters.'],
  'adapter.parameter_mode': ['Full 保留完整因子矩阵；低秩参数更少。', 'Full keeps whole factors; low rank uses fewer weights.'],
  'adapter.factor': ['LoKr 的矩阵拆分方式，-1 自动选择。', 'How LoKr splits each matrix; -1 chooses automatically.'],
  'adapter.rank': ['适配器容量，越大学得越细，文件也越大。', 'Adapter capacity; larger learns more and is bigger.'],
  'adapter.alpha': ['更新的缩放系数，常与 Rank 相同。', 'Scales the updates; often equal to rank.'],
  'adapter.rules': ['按层名单独设置算法、Rank 或学习率。', 'Per-layer algorithm, rank or learning rate.'],
  'adapter.init': ['默认一侧从零开始，训练前输出不变。', 'Default starts one side at zero, so output is unchanged.'],
  'adapter.resume_weights': ['加载上次训练结果，再设置这次要追加的轮数或步数。', 'Load previous weights and set the additional epochs or steps for this run.'],
  'adapter.dropout': ['随机屏蔽部分输出，减轻过拟合。', 'Randomly drops outputs to reduce overfitting.'],
  'adapter.rank_dropout': ['随机屏蔽部分秩通道。', 'Randomly drops rank channels.'],
  'adapter.module_dropout': ['训练时随机跳过整个适配器模块。', 'Randomly skips whole adapter modules.'],
  'adapter.mode': ['底模与适配器的计算方式，通常选自动。', 'How base and adapter are computed; usually automatic.'],
  'adapter.param_dtype': ['适配器参数的存储精度，默认 FP32。', 'Storage precision of adapter weights; FP32 by default.'],
  'adapter.lr_scale': ['按参数类别调整学习率倍率。', 'Learning-rate multipliers by parameter type.'],

  'optimizer.type': ['更新参数的算法，AdamW 最通用。', 'Algorithm that updates weights; AdamW is the default.'],
  'optimizer.lr': ['每次更新的步长，过大不稳，过小学得慢。', 'Update size; too high is unstable, too low is slow.'],
  'optimizer.weight_decay': ['约束权重增长；通常保留默认值，0 关闭。', 'Constrains weight growth; usually keep the default. 0 disables it.'],
  'optimizer.args': ['当前优化器没有专用控件的额外参数。', 'Extra arguments without dedicated controls.'],
  'optimizer.group_lr': ['按模块分别设置学习率，留空统一使用上方值。', 'Per-module rates; blank uses the rate above.'],
  'optimizer.d_coef': ['放大或缩小自动估计的步长。', 'Scales the automatically estimated step.'],
  'optimizer.d0': ['自动步长估计的起始值。', 'Starting value for step estimation.'],
  'optimizer.beta3': ['留空时使用 β2 的平方根；通常保留自动。', 'Blank uses the square root of β2; usually keep automatic.'],
  'optimizer.prodigy_steps': ['估计步长的更新次数，0 为全程估计。', 'Updates spent estimating; 0 estimates throughout.'],
  'optimizer.growth_rate': ['每一步的最大增长倍率；留空时不设上限。', 'Largest growth per step; blank means unlimited.'],
  'optimizer.slice_p': ['估计步长时每隔几个元素取样。', 'Sample every N elements when estimating.'],
  'optimizer.schedulefree_c': ['权重平均的速度，0 为默认方式。', 'Averaging speed; 0 uses the default.'],
  'optimizer.beta2': ['梯度大小的平滑程度，越大越平缓。', 'Smoothing of gradient size; higher is steadier.'],
  'optimizer.min_lr': ['自适应学习率的最小值。', 'Lowest adaptive learning rate.'],
  'optimizer.max_lr': ['自适应学习率的最大值。', 'Highest adaptive learning rate.'],
  'optimizer.lr_bump': ['每次调整学习率的幅度。', 'Size of each learning-rate adjustment.'],
  'optimizer.clip_threshold': ['限制单次更新的幅度，默认 1。', 'Caps the size of each update; default 1.'],

  'scheduler.type': ['学习率随训练变化的方式，cosine 逐渐降低。', 'How the rate changes; cosine lowers it gradually.'],
  'scheduler.warmup_steps': ['开头逐步升高学习率，小于 1 表示比例。', 'Ramp up at the start; below 1 is a fraction.'],
  'scheduler.min_lr_ratio': ['学习率最终降到基础值的比例。', 'Final rate as a fraction of the base rate.'],
  'scheduler.num_cycles': ['学习率先降后升的周期数。', 'Number of fall-and-restart cycles.'],
  'scheduler.power': ['衰减曲线的弯曲程度，1 为直线。', 'Curve shape of the decay; 1 is linear.'],
  'scheduler.decay_steps': ['最后衰减阶段的长度，留空约为 10%。', 'Length of the final decay; blank is about 10%.'],

  'memory.base_precision': ['降低冻结底模精度可省显存，可能影响质量。', 'Lower frozen-weight precision saves memory; may cost quality.'],
  'memory.blocks_to_swap': ['暂放到内存的模型块数，省显存但更慢。', 'Blocks parked in system memory; saves VRAM, runs slower.'],
  'memory.activation_checkpointing': ['重新计算中间结果，省显存但更慢。', 'Recomputes intermediate results; saves memory, runs slower.'],

  'objective.timestep_sampling': ['训练时噪声强度的抽样分布。', 'Distribution of training noise levels.'],
  'objective.logit_mean': ['调高偏向高噪声，调低偏向低噪声。', 'Higher favors noisier steps; lower favors cleaner ones.'],
  'objective.logit_std': ['越大，越多样本落在高低两端。', 'Higher puts more samples at both extremes.'],
  'objective.res_shift_tokens': ['按分辨率计算偏移的两个参考点。', 'Two reference sizes for resolution-based shift.'],
  'objective.res_shift_mu': ['两个参考点对应的偏移系数。', 'Shift coefficients at those reference sizes.'],
  'objective.shift': ['大于 1 偏向高噪声，1 为不偏移。', 'Above 1 favors noisier steps; 1 means no shift.'],
  'objective.mode_scale': ['mode 分布的形状系数。', 'Shape of the mode distribution.'],
  'objective.t_min': ['训练噪声强度的下限。', 'Lowest training noise level.'],
  'objective.t_max': ['训练噪声强度的上限。', 'Highest training noise level.'],
  'objective.loss': ['衡量预测误差的方式，默认 MSE。', 'How prediction error is measured; MSE by default.'],
  'objective.huber_c': ['Huber 损失从小误差过渡到大误差的尺度。', 'Where Huber loss switches from small to large errors.'],
  'objective.weighting': ['按噪声强度给损失加权。', 'Weights the loss by noise level.'],
  'objective.snr_gamma': ['SNR 截断值，默认 5。', 'SNR cap; default 5.'],
  'objective.ip_noise_gamma': ['给输入额外叠加噪声，0 为关闭。', 'Extra input noise; 0 disables it.'],
  'objective.v_pred_like_loss': ['附加 v 预测尺度的损失，0 为关闭。', 'Adds a v-prediction-scale loss; 0 disables it.'],

  'sampling.every_steps': ['每隔多少步生成预览，留空不按步。', 'Preview every N steps; blank disables it.'],
  'sampling.every_epochs': ['每隔多少轮生成预览，留空不按轮。', 'Preview every N epochs; blank disables it.'],
  'sampling.prompts': ['预览使用的提示词，可逐条覆盖参数。', 'Preview prompts; each can override settings.'],
  'sampling.prompts_file': ['追加一个 .txt 或 .toml 提示词文件。', 'Append prompts from a .txt or .toml file.'],
  'sampling.width': ['预览图宽度，单条提示词可覆盖。', 'Preview width; prompts can override it.'],
  'sampling.height': ['预览图高度，单条提示词可覆盖。', 'Preview height; prompts can override it.'],
  'sampling.seed': ['固定种子便于对比训练进度。', 'A fixed seed keeps previews comparable.'],
  'sampling.sampler': ['生成预览图的采样算法。', 'Algorithm used to generate previews.'],
  'sampling.scheduler': ['采样时噪声逐步减少的方式。', 'How noise is reduced while sampling.'],
  'sampling.steps': ['生成一张预览的步数，越多越慢。', 'Steps per preview; more is slower.'],
  'sampling.cfg': ['提示词的影响强度，越大越贴近提示词。', 'Prompt strength; higher follows the prompt more.'],
  'sampling.shift': ['预览采样的时间步偏移。', 'Timestep shift used for previews.'],
  'sampling.er_sde_order': ['ER-SDE 的最高阶数。', 'Highest ER-SDE order.'],
  'sampling.er_sde_s_noise': ['ER-SDE 沿途追加噪声的强度。', 'Extra noise strength during ER-SDE.'],

  'validation.sources': ['只用于验证、不参与训练的图片目录。', 'Folders used only for validation.'],
  'validation.split_ratio': ['从训练图中固定划出做验证的比例。', 'Share of training images held out for validation.'],
  'validation.every_steps': ['每隔多少步计算一次验证损失。', 'Validate every N steps.'],
  'validation.every_epochs': ['每隔多少轮计算一次验证损失。', 'Validate every N epochs.'],
  'validation.max_images': ['每次验证最多使用的图片数。', 'Most images used per validation.'],
  'validation.timesteps': ['计算验证损失时使用的噪声强度。', 'Noise levels used for validation loss.'],
  'validation.seed': ['验证加噪使用的随机种子。', 'Random seed for validation noise.'],

  'checkpoint.name': ['导出权重的文件名前缀。', 'File name prefix for exported weights.'],
  'checkpoint.save_dtype': ['导出权重的精度，FP32 文件更大。', 'Precision of exported weights; FP32 is larger.'],
  'checkpoint.output_dir': ['训练权重的保存位置。', 'Where trained weights are saved.'],
  'checkpoint.save_every_steps': ['每隔多少步导出一次权重。', 'Export weights every N steps.'],
  'checkpoint.save_every_epochs': ['每隔多少轮导出一次权重。', 'Export weights every N epochs.'],
  'checkpoint.keep_last_n': ['只保留最近几次按步导出的权重。', 'Keep only the latest step exports.'],
  'checkpoint.save_state_every_steps': ['按步或按轮保存训练进度，供中断后继续。', 'Save training progress by step or epoch to resume after an interruption.'],
  'checkpoint.state_dir': ['保存完整训练进度，留空跟随默认目录。', 'Stores recovery points; blank uses the default directory.'],
  'sampling.output_dir': ['保存训练预览图，留空跟随默认目录。', 'Stores training previews; blank uses the default directory.'],
  'checkpoint.resume': ['从保存的完整状态继续训练。', 'Continue from a saved training state.'],

  'logging.output_dir': ['保存任务日志和 TensorBoard，留空跟随默认目录。', 'Stores logs and TensorBoard data; blank uses the default directory.'],
  'logging.level': ['训练日志记录的详细程度。', 'How much detail the training log records.'],
  'logging.events_path': ['记录训练进度与损失，留空使用默认日志位置。', 'Records training progress and loss; blank uses the default log location.'],
};

export const FIELD_HELP: Record<string, Copy> = {
  'dataset.caption.shuffle': ['TXT 只打乱未保留的标签；分类 JSON 只打乱可变分组内的标签，固定信息和自然语言不动。使用文本缓存时，从预生成的随机变体中选择。', 'Shuffles unprotected TXT tags or tags within variable JSON groups. Fixed information and natural language stay unchanged. Text caching selects from pre-generated random variants.'],
  'dataset.caption.keep_tokens': ['仅用于 TXT：前 N 个标签不参与打乱或标签丢弃。即使关闭打乱，只要启用了标签丢弃，此设置仍然有效。分类 JSON 按字段分组处理，不使用此计数。', 'For TXT captions, protects the first N tags from shuffling and tag dropout. Still applies with shuffling off when tag dropout is enabled. Structured JSON uses its fixed fields instead of this count.'],
  'sampling.enabled': ['按设定间隔生成预览图，需要至少一条提示词或提示词文件。生成预览会占用时间，不参与梯度更新。', 'Generates previews at the chosen intervals. Requires at least one prompt or a prompt file. Preview generation takes time and does not update training gradients.'],
  'validation.enabled': ['使用固定验证图片和噪声计算损失，不对验证图片反向更新。需要设置验证划分比例或单独的验证数据来源。', 'Measures loss with fixed validation images and noise, without updating weights from validation images. Set a validation split or a separate validation data source.'],
  'loop.ema': ['在 CPU 维护适配器权重的指数移动平均，额外保存 EMA 权重用于对比，会增加内存和文件占用。训练预览仍使用普通权重。', 'Maintains an exponential moving average of adapter weights on the CPU and exports an additional set of EMA weights. Uses extra memory and storage. Training previews still use the regular weights.'],
  'model.family': ['决定可用的模型文件、训练方式和默认参数。名称中的 B 表示十亿个主模型参数，不含文本编码器与 VAE；Klein 的实际规模由模型版本决定。', 'Determines the model files, training modes and defaults. B denotes billion backbone parameters, excluding text encoders and the VAE; the Klein variant determines its actual size.'],
  'dataset.sources': ['参与训练的图片目录。重复次数表示每轮使用这组图片的遍数，数值越大，这组图片在训练中的占比越高。图片没有标签文件时，可以填写“无标签时的描述”作为标签。', 'Image folders used for training. Repeats set how many times a folder is used per epoch; higher values give it a larger share. Text for uncaptioned images is used when an image has no caption file.'],
  'dataset.flip': ['训练时随机左右翻转图片，让模型看到更多变化。开启后会多缓存一份翻转后的图像编码。画面含文字或左右不对称的特征时不建议开启。', 'Randomly mirrors images during training for more variety. Caches an extra flipped encoding. Avoid it when images contain text or asymmetric features.'],
  'dataset.masked_loss': ['使用同名的 .mask.png 遮罩或图片自身的透明通道控制每个区域参与训练的程度：白色或不透明区域正常训练，黑色或完全透明的区域不参与。没有遮罩和透明像素的图片按整张训练。', 'Uses a matching .mask.png or the image alpha channel to weight each region: white or opaque areas train normally, black or fully transparent areas are ignored. Images without masks or transparent pixels train as a whole.'],
  'dataset.num_workers': ['后台读取和处理图片的进程数。0 表示在训练进程内读取，最稳定，Windows 建议保持 0。图像已缓存时读取负担较小，通常不需要增加。', 'Background processes that load images. 0 loads inside the training process and is the most stable choice on Windows. With cached images the loading work is small, so more workers rarely help.'],
  'dataset.cache_dir': ['保存可复用的图像编码和文本特征。留空使用“设置 → 存储路径”中的缓存目录；指定其他目录后会在新位置生成缓存。', 'Stores reusable image and text features. Blank uses the cache directory in Settings → Storage paths; choosing another directory creates caches there.'],
  'dataset.caption.trigger_word': ['放在标签开头的触发词，不参与打乱和丢弃；标签中已有的同名词会移到开头。训练后在提示词中写这个词即可调用学到的内容。', 'A trigger placed at the start of every caption and never shuffled or dropped; an identical existing tag moves to the front. Use it in prompts to invoke what was learned.'],
  'dataset.caption.prefix': ['加在每条标签最前面的固定文字，位于触发词之前，不参与打乱和丢弃。', 'Fixed text placed before every caption, ahead of the trigger word. It is never shuffled or dropped.'],
  'dataset.caption.suffix': ['加在每条标签末尾的固定文字，不参与打乱和丢弃。', 'Fixed text placed after every caption. It is never shuffled or dropped.'],
  'dataset.caption.separator': ['TXT 标签中分隔各个标签的字符，默认为英文逗号。打乱、丢弃和保留前几个标签都按它拆分。', 'Character separating tags in TXT captions, a comma by default. Shuffling, dropout and kept tags all split on it.'],
  'dataset.caption.caption_dropout': ['按此概率把整条标签换成空文本，让模型同时学习不看标签的生成，有助于提示词引导（CFG）。0 表示关闭，常用 0～0.1。', 'Replaces the whole caption with empty text at this rate so the model also learns unconditioned generation, which helps CFG. 0 disables it; 0–0.1 is common.'],
  'dataset.caption.wildcard': ['允许在标签中写 {红色|蓝色}，每次训练随机选择其中一项。', 'Allows {red|blue} in captions; one option is picked at random each time.'],
  'dataset.caption.cache_variants': ['使用文本缓存时，每张图预先生成多少种随机标签组合。只在打乱、标签丢弃或通配符生效时有意义；数值越大，变化越多，缓存也越大。', 'Random caption variants prepared per image when text is cached. Only useful with shuffling, tag dropout or wildcards; more variants add variety and cache size.'],
  'adapter.rules': ['按层名匹配，为匹配的层单独设置算法、Rank、Alpha、Factor 或学习率；算法选 none 可排除该层。每层只使用第一条匹配的规则，规则也能加入作用范围之外的层。写法为通配符（如 blocks.*），以 re: 开头时按正则表达式匹配。', 'Matches layers by name to set their algorithm, rank, alpha, factor or learning rate; algorithm none excludes a layer. Each layer uses the first matching rule, and a rule can add layers outside the scope. Use globs such as blocks.*, or a re: prefix for regular expressions.'],
  'adapter.dora': ['DoRA 把权重拆成幅度和方向分别学习，效果通常更接近全量微调，但训练更慢、显存占用更高。', 'DoRA learns weight magnitude and direction separately. Results are often closer to full fine-tuning, at the cost of speed and memory.'],
  'adapter.rs_lora': ['按 Alpha ÷ √Rank 缩放更新（普通方式为 Alpha ÷ Rank），Rank 较大时训练更稳定。开启后更新幅度会变化，需要重新调整学习率或 Alpha。', 'Scales updates by alpha ÷ √rank instead of alpha ÷ rank, which is steadier at high ranks. The update size changes, so revisit the learning rate or alpha.'],
  'adapter.init': ['默认：一侧矩阵从零开始，训练开始时输出与底模一致。随机权重＋零值缩放：两侧都随机初始化，再用从 0 开始的可训练缩放控制输出。', 'Default starts one matrix at zero, so the output initially matches the base model. Random weights + zero scale initializes both sides randomly and controls the output with a trainable scale that starts at 0.'],
  'adapter.dropout': ['训练时按此比例随机屏蔽适配器输出，减轻过拟合。0 表示关闭，常用 0～0.1。', 'Randomly masks adapter outputs at this rate to reduce overfitting. 0 disables it; 0–0.1 is common.'],
  'adapter.rank_dropout': ['训练时按此比例随机屏蔽部分秩通道。0 表示关闭。', 'Randomly masks rank channels at this rate during training. 0 disables it.'],
  'adapter.module_dropout': ['训练时按此概率跳过整个适配器模块，直接使用底模输出。0 表示关闭；多卡显存分片不支持。', 'Skips whole adapter modules at this rate and uses the base output instead. 0 disables it; memory sharding does not support it.'],
  'adapter.mode': ['分开计算：底模和适配器各自计算后相加，不改变底模权重精度。合并计算：先把适配器合并进权重再计算，DoRA 需要这种方式。自动：能分开计算时分开计算，否则合并。', 'Separate computes the base model and the adapter independently and adds them, keeping base precision. Merged folds the adapter into the weight first, which DoRA requires. Automatic uses separate computation when possible.'],
  'adapter.param_dtype': ['适配器可训练参数的存储精度。默认 FP32 最稳定；BF16 节省显存，但较小的更新可能被舍入。', 'Storage precision of trainable adapter parameters. FP32 is the stable default; BF16 saves memory but small updates may be rounded away.'],
  'adapter.lr_scale': ['按参数类别设置学习率倍率。例如 LoRA+ 常把 up 设为 16，LoKr 可单独调整 w1。不熟悉时留空。', 'Learning-rate multipliers by parameter type. LoRA+ commonly sets up to 16, and LoKr can adjust w1 separately. Leave empty if unsure.'],
  'checkpoint.output_dir': ['导出权重的保存根目录，任务按项目、版本和任务 ID 分开保存。未单独指定的恢复点和日志也保存在这里。', 'Root for exported weights, organized by project, version and job ID. Recovery points and logs also go here unless configured separately.'],
  'checkpoint.state_dir': ['保存续训所需的权重、优化器、步数与随机状态。留空使用“设置 → 存储路径”中的恢复点目录；该项也未设置时随训练产物保存。自定义目录下按项目、版本和任务分开存放。', 'Stores weights, optimizer, step and random state for resuming. Blank uses the recovery directory in Settings → Storage paths, or the training output if unset. Custom roots are organized by project, version and job.'],
  'sampling.output_dir': ['保存训练预览图。留空使用“设置 → 存储路径”中的采样图目录；该项也未设置时保存在项目版本的 samples 目录。自定义目录下按项目、版本和任务分开存放。', 'Stores training previews. Blank uses the sample directory in Settings → Storage paths, or the project version’s samples folder if unset. Custom roots are organized by project, version and job.'],
  'checkpoint.save_on_finish': ['训练结束时导出最终权重。关闭后只保留按步或按轮导出的文件。', 'Exports the final weights when training ends. When off, only step or epoch exports are kept.'],
  'checkpoint.keep_last_n': ['只保留最近 N 组按步导出的权重，更早的自动删除；按轮导出和最终权重不受影响。留空保留全部。', 'Keeps only the latest N step exports and deletes older ones; epoch exports and final weights are unaffected. Blank keeps all.'],
  'validation.sources': ['只用于验证、不参与训练的图片目录。设置后可以不从训练图中划分验证集。', 'Image folders used only for validation, never for training. With these set, no training images need to be held out.'],
  'validation.every_steps': ['每隔多少次优化更新计算一次验证损失。留空不按步验证。', 'Computes validation loss every N optimizer updates. Blank disables step-based validation.'],
  'validation.every_epochs': ['每隔多少轮计算一次验证损失。留空不按轮验证。', 'Computes validation loss every N epochs. Blank disables epoch-based validation.'],
  'validation.seed': ['验证加噪使用的随机种子。保持不变，不同时间点的验证损失才能直接比较。', 'Random seed for validation noise. Keep it fixed so validation losses stay comparable over time.'],
  'logging.level': ['调试级别额外记录设备与精度、各阶段耗时、数据分桶、优化器与调度器、恢复点保存和采样等细节；在任务日志中打开“调试日志”后显示，默认隐藏。信息级别只记录常规进度；警告级别只记录警告和错误。修改后对新启动的任务生效。', 'Debug additionally records device and precision choices, phase timings, buckets, optimizer and scheduler settings, recovery saves and sampling. Turn on Debug in the job log to show these lines; they are hidden by default. Info records routine progress; Warning records only warnings and errors. Changes apply to newly started jobs.'],
  'logging.output_dir': ['保存控制台日志、训练事件与 TensorBoard 数据。留空使用“设置 → 存储路径”中的日志目录；该项也未设置时随训练产物保存。自定义目录下按项目、版本和任务分开存放。', 'Stores console logs, training events and TensorBoard data. Blank uses the log directory in Settings → Storage paths, or the training output if unset. Custom roots are organized by project, version and job.'],
  'logging.events_path': ['记录训练进度、损失等事件的文件，默认名为 events.jsonl。设置了日志保存目录时使用该目录；否则使用此文件的父目录作为日志根目录。', 'Records training progress, losses and other events, named events.jsonl by default. Uses the configured log directory, or this file’s parent as the log root.'],
};

const MODEL_PATH_HINTS: Record<string, Record<string, Copy>> = {
  anima: {
    dit_path: ['Anima 主模型权重文件。', 'Anima main model weights.'],
    text_encoder_path: ['Qwen3-0.6B 文本编码器。', 'Qwen3-0.6B text encoder.'],
    vae_path: ['Qwen-Image VAE 文件。', 'Qwen-Image VAE file.'],
    tokenizer_path: ['留空使用内置分词器。', 'Blank uses the built-in tokenizer.'],
  },
  flux2: {
    dit_path: ['Klein 基础版完整目录或单文件。', 'Klein base folder or single file.'],
    text_encoder_path: ['完整模型目录可留空。', 'Optional with a full model folder.'],
    vae_path: ['完整模型目录可留空。', 'Optional with a full model folder.'],
    tokenizer_path: ['模型目录内含分词器时可留空。', 'Optional when the model folder includes one.'],
  },
  krea2: {
    dit_path: ['Krea 2 Raw 主模型，BF16 或 FP8 文件。', 'Krea 2 Raw main model, BF16 or FP8.'],
    text_encoder_path: ['Qwen3-VL-4B 文本编码器。', 'Qwen3-VL-4B text encoder.'],
    vae_path: ['Qwen-Image VAE，与 Anima 通用。', 'Qwen-Image VAE, shared with Anima.'],
    tokenizer_path: ['留空使用模型自带的分词器。', 'Blank uses the bundled tokenizer.'],
  },
  sdxl: {
    dit_path: ['完整 SDXL 模型文件或 Diffusers 目录。', 'Full SDXL checkpoint or Diffusers folder.'],
    text_encoder_path: ['留空使用模型内含的 CLIP-L。', 'Blank uses the bundled CLIP-L.'],
    text_encoder_2_path: ['留空使用模型内含的 CLIP-G。', 'Blank uses the bundled CLIP-G.'],
    vae_path: ['留空使用模型内含的 VAE。', 'Blank uses the bundled VAE.'],
    tokenizer_path: ['可选，留空自动读取模型目录。', 'Optional; blank reads the model folder.'],
  },
};

const GENERIC_MODEL_PATH_HINTS: Record<string, Copy> = {
  dit_path: ['主模型权重，可从已登记模型中选择。', 'Main model weights; pick a registered model or browse.'],
  text_encoder_path: ['把标签文字转换为特征的模型。', 'Model that turns captions into features.'],
  text_encoder_2_path: ['第二个文本编码器。', 'Second text encoder.'],
  vae_path: ['在图片与潜空间之间转换的模型。', 'Converts between images and latents.'],
  tokenizer_path: ['可选，留空自动选择分词器。', 'Optional; blank picks the tokenizer automatically.'],
};

/** Presets may leave model files empty; applying one then keeps the configuration's files. */
export function modelPathHint(family: string | undefined, field: string, english: boolean, preset = false) {
  if (preset) return english ? 'Blank keeps the training configuration’s model.' : '留空时沿用训练配置中的模型。';
  const copy = (family && MODEL_PATH_HINTS[family]?.[field]) || GENERIC_MODEL_PATH_HINTS[field];
  return copy?.[english ? 1 : 0];
}
