/**
 * Parameter copy shown in the training and preset editors.
 * FIELD_HINTS: one short line under every non-switch field; switches have none.
 * FIELD_HELP: the detailed text behind the help button, where the schema text is too terse.
 */
type Copy = [string, string];

export const FIELD_HINTS: Record<string, Copy> = {
  'model.family': ['选择要训练的模型，B 表示十亿参数。', 'The model to train; B means billion parameters.'],
  'training.backbone_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.text_encoder_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.text_encoder_2_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.llm_adapter_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.self_attn_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.cross_attn_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.mlp_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'training.modulation_lr': ['留空沿用已有学习率；0 冻结对应参数。', 'Blank inherits the learning rate; 0 freezes these parameters.'],
  'dataset.caption.weighted': ['按括号权重编码 SDXL 标签和采样提示词。', 'Apply bracket weights to SDXL captions and preview prompts.'],
  'objective.noise_offset': ['改变各通道的整体噪声，设为 0 关闭。', 'Adds channel-wide noise; set to 0 to disable.'],
  'objective.multires_noise_iterations': ['叠加低分辨率噪声的层数，设为 0 关闭。', 'Number of low-resolution noise layers; set to 0 to disable.'],
  'objective.multires_noise_discount': ['越小，后续低分辨率层的影响越弱。', 'Lower values reduce the contribution of later layers.'],
  'optimizer.cpu_offload': ['将 AdamW 状态和更新放到 CPU，节省显存。', 'Keep AdamW states and updates on the CPU to save VRAM.'],
  'optimizer.exclude_bias_norm_from_weight_decay': ['偏置与归一化参数的权重衰减设为 0。', 'Use zero weight decay for biases and normalization parameters.'],
  'training.mode': ['LoRA／LoKr 训练附加权重；全量微调直接更新模型。', 'LoRA / LoKr trains added weights; full fine-tuning updates the model.'],
  'training.resume_weights': ['从导出的全量模型继续微调，留空从底模开始。', 'Continue from an exported full model; blank starts from the base.'],
  'model.tokenizer_path': ['留空自动使用模型目录或内置分词器。', 'Blank uses the model folder or built-in tokenizers.'],
  'model.prediction_type': ['须与模型一致，常规 SDXL 选 ε 预测。', 'Must match the model; standard SDXL uses epsilon.'],
  'model.sdxl_max_token_length': ['标签最多编码的长度，超出部分截断。', 'Longest caption encoded; the rest is truncated.'],
  'model.flux2_variant': ['Klein 基础版的规模，完整目录可自动识别。', 'Klein base size; full folders are detected automatically.'],
  'model.krea2_variant': ['未登记的文件需确认是 Raw 还是 Turbo。', 'Confirm Raw or Turbo for unregistered files.'],
  'model.attention': ['注意力的计算方式，影响速度和显存。', 'How attention is computed; affects speed and memory.'],

  'dataset.sources': ['每个目录可单独设置重复次数和用途。', 'Each folder has its own repeats and purpose.'],
  'dataset.resolution_mode': ['分桶统一训练面积；原生保留每张图的尺寸。', 'Buckets share one area; native keeps each image size.'],
  'dataset.resolutions': ['每个分桶的基准边长，多个用逗号分隔。', 'Base side per bucket; separate several with commas.'],
  'dataset.image_fit': ['图片与训练尺寸比例不同时补边或裁切。', 'Pad or crop when the image and training shape differ.'],
  'dataset.native_max_pixels': ['单张图片允许的最大面积。', 'Largest area allowed for one image.'],
  'dataset.native_max_side': ['宽或高超过此值时等比缩小。', 'Wider or taller images are scaled down.'],
  'dataset.native_overflow': ['图片超出尺寸上限时的处理方式。', 'What happens when an image exceeds the limits.'],
  'dataset.aspect_ratio_limit': ['分桶最宽的比例，2 表示最宽 2:1。', 'Widest bucket shape; 2 means up to 2:1.'],
  'dataset.area_tolerance': ['分桶面积可偏离基准面积的比例。', 'How far a bucket area may differ from the base.'],
  'dataset.bucket_step': ['分桶宽高的间隔，留空通常为 64。', 'Spacing between bucket sizes; blank is usually 64.'],
  'dataset.batch_size': ['每张显卡每批的图片数。', 'Images in each batch on every GPU.'],
  'dataset.text_encoding': ['标签的编码方式，缓存可节省显存。', 'How captions are encoded; caching saves memory.'],
  'dataset.num_workers': ['后台读取图片的进程数，Windows 建议 0。', 'Background loaders; use 0 on Windows.'],
  'dataset.cache_dir': ['图像与文本缓存的位置，留空放在输出目录。', 'Where caches are kept; blank uses the output folder.'],

  'dataset.caption.trigger_word': ['放在标签开头，不参与打乱和丢弃。', 'Placed first; never shuffled or dropped.'],
  'dataset.caption.prefix': ['加在每条标签最前面的固定文字。', 'Fixed text before every caption.'],
  'dataset.caption.suffix': ['加在每条标签末尾的固定文字。', 'Fixed text after every caption.'],
  'dataset.caption.separator': ['拆分 TXT 标签的字符，默认为逗号。', 'Character that splits TXT tags; comma by default.'],
  'dataset.caption.keep_tokens': ['开头几个标签位置固定，不被打乱或丢弃。', 'Leading tags stay in place and are never dropped.'],
  'dataset.caption.tag_dropout': ['每个标签被随机去掉的概率，设为 0 不丢弃标签。', 'Chance to drop each tag; set to 0 to keep all tags.'],
  'dataset.caption.caption_dropout': ['整条标签被置空的概率，设为 0 不置空。', 'Chance to blank the whole caption; set to 0 to keep it.'],
  'dataset.caption.cache_variants': ['缓存文本时每张图预生成的随机组合数。', 'Random caption variants cached per image.'],

  'loop.gpu_count': ['1 为单卡；多卡可选择数据并行或显存分片。', '1 uses one GPU; several can split data or memory.'],
  'loop.distributed_strategy': ['DDP 通常训练更快；FSDP 更省显存，但增加通信开销。', 'DDP is usually faster; FSDP saves memory with extra communication.'],
  'loop.grad_accum': ['累积几个批次再更新一次参数。', 'Batches accumulated before each update.'],
  'loop.epochs': ['完整遍历全部训练图片的次数。', 'Passes over the whole training set.'],
  'loop.max_steps': ['最多更新多少次，留空按轮数结束。', 'Most updates to run; blank stops by epochs.'],
  'loop.mixed_precision': ['训练运算使用的精度，BF16 最常用。', 'Precision used for training math; BF16 is typical.'],
  'loop.seed': ['固定后可重现相同的数据顺序和噪声。', 'Fixes data order and noise for repeatable runs.'],
  'loop.ema_decay': ['越接近 1，平均权重变化越慢。', 'Closer to 1 averages more slowly.'],
  'loop.nan_skip_limit': ['连续出现无效数值时最多跳过的步数。', 'Invalid steps skipped in a row before stopping.'],
  'loop.log_every': ['每隔多少步记录一次训练指标。', 'Record metrics every N steps.'],

  'adapter.algo': ['附加权重的结构，LoRA 最常用。', 'Structure of the added weights; LoRA is most common.'],
  'adapter.preset': ['选择 LoRA／LoKr 作用的模型层。', 'Which layers receive adapters.'],
  'adapter.layer_types': ['只训练线性层，或同时训练卷积层。', 'Linear layers only, or convolutions as well.'],
  'adapter.conv_rank': ['3×3 等卷积层的 Rank，留空与 Rank 相同。', 'Rank of 3×3 and larger convolutions; blank follows Rank.'],
  'adapter.conv_alpha': ['这些卷积层的缩放系数，留空与 Alpha 相同。', 'Scale for those convolutions; blank follows Alpha.'],
  'adapter.parameter_mode': ['Full 保留完整因子矩阵；低秩参数更少。', 'Full keeps whole factors; low rank uses fewer weights.'],
  'adapter.factor': ['LoKr 的矩阵拆分方式，-1 自动选择。', 'How LoKr splits each matrix; -1 chooses automatically.'],
  'adapter.rank': ['适配器容量，越大学得越细，文件也越大。', 'Adapter capacity; larger learns more and is bigger.'],
  'adapter.alpha': ['更新的缩放系数，常与 Rank 相同。', 'Scales the updates; often equal to rank.'],
  'adapter.tlora_min_rank': ['噪声最大时保留的秩，留空为 Rank 的一半。', 'Ranks kept at the noisiest step; blank is half the rank.'],
  'adapter.tlora_power': ['可用的秩随噪声变化的快慢，1 为线性。', 'How fast ranks open as noise falls; 1 is linear.'],
  'adapter.rules': ['按层名单独设置算法、Rank 或学习率。', 'Per-layer algorithm, rank or learning rate.'],
  'adapter.init': ['默认一侧从零开始，训练前输出不变。', 'Default starts one side at zero, so output is unchanged.'],
  'adapter.dora_axis': ['幅度归一化使用的通道，继续训练时须与原权重一致。', 'Channels used for magnitude normalization; keep the original axis when resuming.'],
  'adapter.dora_merge_dtype': ['合并底模与 DoRA 权重时的计算精度。', 'Computation precision when merging the base model and DoRA weights.'],
  'adapter.resume_weights': ['加载上次训练结果，再设置这次要追加的轮数或步数。', 'Load previous weights and set the additional epochs or steps for this run.'],
  'adapter.dropout': ['随机屏蔽部分输出，减轻过拟合；设为 0 关闭。', 'Randomly drops outputs to reduce overfitting; set to 0 to disable.'],
  'adapter.rank_dropout': ['随机屏蔽部分秩通道，设为 0 关闭。', 'Randomly drops rank channels; set to 0 to disable.'],
  'adapter.module_dropout': ['训练时随机跳过整个适配器模块，设为 0 关闭。', 'Randomly skips whole adapter modules; set to 0 to disable.'],
  'adapter.mode': ['底模与适配器的计算方式，通常选自动。', 'How base and adapter are computed; usually automatic.'],
  'adapter.param_dtype': ['适配器参数的存储精度，默认 FP32。', 'Storage precision of adapter weights; FP32 by default.'],
  'adapter.lr_scale': ['按参数类别调整学习率倍率。', 'Learning-rate multipliers by parameter type.'],

  'optimizer.type': ['更新参数的算法，AdamW 最通用。', 'Algorithm that updates weights; AdamW is the default.'],
  'optimizer.lr': ['每次更新的步长，过大不稳，过小学得慢。', 'Update size; too high is unstable, too low is slow.'],
  'optimizer.weight_decay': ['约束权重增长；通常保留默认值，设为 0 关闭。', 'Constrains weight growth; usually keep the default. Set to 0 to disable.'],
  'optimizer.args': ['当前优化器没有专用控件的额外参数。', 'Extra arguments without dedicated controls.'],
  'optimizer.group_lr': ['按模块分别设置学习率，留空统一使用上方值。', 'Per-module rates; blank uses the rate above.'],
  'optimizer.d_coef': ['放大或缩小自动估计的步长。', 'Scales the automatically estimated step.'],
  'optimizer.d0': ['自动步长估计的起始值。', 'Starting value for step estimation.'],
  'optimizer.beta3': ['留空时使用 β2 的平方根；通常保留自动。', 'Blank uses the square root of β2; usually keep automatic.'],
  'optimizer.prodigy_steps': ['估计步长的更新次数，0 为全程估计。', 'Updates spent estimating; 0 estimates throughout.'],
  'optimizer.growth_rate': ['每一步的最大增长倍率；留空时不设上限。', 'Largest growth per step; blank means unlimited.'],
  'optimizer.slice_p': ['估计步长时每隔几个元素取样。', 'Sample every N elements when estimating.'],
  'optimizer.schedulefree_c': ['权重平均的速度，0 为默认方式。', 'Averaging speed; 0 uses the default.'],
  'optimizer.beta2': ['梯度大小的平滑程度，越大越平缓。', 'Smoothing of gradient size; higher is steadier.'],
  'optimizer.min_lr': ['自适应学习率的最小值。', 'Lowest adaptive learning rate.'],
  'optimizer.max_lr': ['自适应学习率的最大值。', 'Highest adaptive learning rate.'],
  'optimizer.lr_bump': ['每次调整学习率的幅度。', 'Size of each learning-rate adjustment.'],
  'optimizer.clip_threshold': ['限制单次更新的幅度，默认 1。', 'Caps the size of each update; default 1.'],

  'scheduler.type': ['学习率随训练步数变化的方式。', 'How the learning rate changes over training steps.'],
  'scheduler.warmup_steps': ['开头逐步升高学习率；设为 0 关闭，0 到 1 之间表示比例。', 'Ramp up at the start; set to 0 to disable. Values between 0 and 1 are fractions.'],
  'scheduler.min_lr_ratio': ['学习率最终降到基础值的比例。', 'Final rate as a fraction of the base rate.'],
  'scheduler.num_cycles': ['学习率先降后升的周期数。', 'Number of fall-and-restart cycles.'],
  'scheduler.power': ['衰减曲线的弯曲程度，1 为直线。', 'Curve shape of the decay; 1 is linear.'],
  'scheduler.decay_steps': ['最后衰减阶段的长度，留空约为 10%。', 'Length of the final decay; blank is about 10%.'],

  'memory.base_precision': ['降低冻结底模精度可省显存，可能影响质量。', 'Lower frozen-weight precision saves memory; may cost quality.'],
  'memory.blocks_to_swap': ['暂放到内存的模型块数，省显存但更慢；设为 0 关闭。', 'Blocks parked in system memory; saves VRAM, runs slower. Set to 0 to disable.'],
  'memory.activation_checkpointing': ['大幅减少显存，训练稍慢；显存不够时优先开启。', 'Much less memory, slightly slower; turn on first when memory is short.'],
  'memory.vae_encode_batch_size': ['每次 VAE 编码的图片数，默认 1；与训练批量分开。', 'Images per VAE encode, 1 by default; separate from the training batch.'],

  'objective.timestep_sampling': ['训练时噪声强度的抽样分布。', 'Distribution of training noise levels.'],
  'objective.logit_mean': ['调高偏向高噪声，调低偏向低噪声。', 'Higher favors noisier steps; lower favors cleaner ones.'],
  'objective.logit_std': ['越大，越多样本落在高低两端。', 'Higher puts more samples at both extremes.'],
  'objective.res_shift_tokens': ['按分辨率计算偏移的两个参考点。', 'Two reference sizes for resolution-based shift.'],
  'objective.res_shift_mu': ['两个参考点对应的偏移系数。', 'Shift coefficients at those reference sizes.'],
  'objective.shift': ['大于 1 偏向高噪声，1 为不偏移。', 'Above 1 favors noisier steps; 1 means no shift.'],
  'objective.mode_scale': ['mode 分布的形状系数。', 'Shape of the mode distribution.'],
  'objective.t_min': ['训练噪声强度的下限。', 'Lowest training noise level.'],
  'objective.t_max': ['训练噪声强度的上限。', 'Highest training noise level.'],
  'objective.loss': ['衡量预测误差的方式，默认 MSE。', 'How prediction error is measured; MSE by default.'],
  'objective.huber_c': ['Huber 损失从小误差过渡到大误差的尺度。', 'Where Huber loss switches from small to large errors.'],
  'objective.weighting': ['按噪声强度给损失加权。', 'Weights the loss by noise level.'],
  'objective.snr_gamma': ['SNR 截断值，默认 5。', 'SNR cap; default 5.'],
  'objective.ip_noise_gamma': ['给输入额外叠加噪声，设为 0 关闭。', 'Extra input noise; set to 0 to disable.'],
  'objective.v_pred_like_loss': ['附加 v 预测尺度的损失，设为 0 关闭。', 'Adds a v-prediction-scale loss; set to 0 to disable.'],

  'sampling.every_steps': ['每隔多少步生成预览，留空关闭。', 'Preview every N steps; leave blank to disable.'],
  'sampling.every_epochs': ['每隔多少轮生成预览，留空关闭。', 'Preview every N epochs; leave blank to disable.'],
  'sampling.prompts': ['预览使用的提示词，可逐条覆盖参数。', 'Preview prompts; each can override settings.'],
  'sampling.prompts_file': ['追加一个 .txt 或 .toml 提示词文件。', 'Append prompts from a .txt or .toml file.'],
  'sampling.width': ['预览图宽度，单条提示词可覆盖。', 'Preview width; prompts can override it.'],
  'sampling.height': ['预览图高度，单条提示词可覆盖。', 'Preview height; prompts can override it.'],
  'sampling.seed': ['0 表示每次训练随机一个种子；手动输入种子值会固定训练时使用的种子。', '0 picks a random seed per run; a seed you enter stays fixed for training.'],
  'sampling.noise': ['选择适配器融合与噪声规则，仅影响采样。', 'Selects adapter merging and noise rules for sampling only.'],
  'sampling.adapter_merge_dtype': ['自动跟随底模精度；可按外部加载方式指定。', 'Auto follows the base model precision; override it to match an external loader.'],
  'sampling.sampler': ['生成预览图的采样算法。', 'Algorithm used to generate previews.'],
  'sampling.scheduler': ['采样时噪声逐步减少的方式。', 'How noise is reduced while sampling.'],
  'sampling.steps': ['生成一张预览的步数，越多越慢。', 'Steps per preview; more is slower.'],
  'sampling.cfg': ['提示词的影响强度，越大越贴近提示词。', 'Prompt strength; higher follows the prompt more.'],
  'sampling.shift': ['预览采样的时间步偏移。', 'Timestep shift used for previews.'],
  'sampling.er_sde_order': ['ER-SDE 的最高阶数。', 'Highest ER-SDE order.'],
  'sampling.er_sde_s_noise': ['ER-SDE 沿途追加噪声的强度，设为 0 关闭沿途噪声。', 'Extra noise strength during ER-SDE; set to 0 to disable these increments.'],

  'validation.sources': ['只用于验证、不参与训练的图片目录。', 'Folders used only for validation.'],
  'validation.split_ratio': ['从训练图中固定划出做验证的比例，设为 0 不自动划分。', 'Share of training images held out for validation; set to 0 to skip automatic splitting.'],
  'validation.every_steps': ['每隔多少步计算一次验证损失，留空关闭。', 'Validate every N steps; leave blank to disable.'],
  'validation.every_epochs': ['每隔多少轮计算一次验证损失，留空关闭。', 'Validate every N epochs; leave blank to disable.'],
  'validation.max_images': ['每次验证最多使用的图片数。', 'Most images used per validation.'],
  'validation.timesteps': ['计算验证损失时使用的噪声强度。', 'Noise levels used for validation loss.'],
  'validation.seed': ['验证加噪使用的随机种子。', 'Random seed for validation noise.'],

  'checkpoint.name': ['导出权重的文件名前缀。', 'File name prefix for exported weights.'],
  'checkpoint.metadata_title': ['留空使用权重文件名前缀。', 'Blank uses the weight file name prefix.'],
  'checkpoint.metadata_author': ['模型作者或组织名称。', 'Model author or organization.'],
  'checkpoint.metadata_description': ['模型用途与说明，支持多行。', 'Model purpose and description; supports multiple lines.'],
  'checkpoint.metadata_license': ['许可证名称、条款或链接。', 'License name, terms or link.'],
  'checkpoint.metadata_merged_from': ['合并使用的来源模型名称。', 'Names of source models used in a merge.'],
  'checkpoint.metadata_tags': ['多个标签用逗号分隔。', 'Separate tags with commas.'],
  'checkpoint.metadata_usage_hint': ['供模型使用者参考的出图设置。', 'Suggested generation settings for model users.'],
  'checkpoint.metadata_trigger_phrase': ['写入模型信息，不修改训练标签。', 'Stored in model information; does not change training captions.'],
  'checkpoint.save_dtype': ['导出权重及 DoRA 幅度的精度，FP32 文件更大。', 'Precision of exported weights and DoRA magnitudes; FP32 is larger.'],
  'checkpoint.output_dir': ['训练权重的保存位置。', 'Where trained weights are saved.'],
  'checkpoint.save_every_steps': ['每隔多少步导出一次权重，留空关闭。', 'Export weights every N steps; leave blank to disable.'],
  'checkpoint.save_every_epochs': ['每隔多少轮导出一次权重，留空关闭。', 'Export weights every N epochs; leave blank to disable.'],
  'checkpoint.keep_last_n': ['只保留最近几次按步导出的权重。', 'Keep only the latest step exports.'],
  'checkpoint.save_state_every_steps': ['按步或按轮保存训练进度，供中断后继续。', 'Save training progress by step or epoch to resume after an interruption.'],
  'checkpoint.state_dir': ['保存完整训练进度，留空跟随默认目录。', 'Stores recovery points; blank uses the default directory.'],
  'sampling.output_dir': ['保存训练预览图，留空跟随默认目录。', 'Stores training previews; blank uses the default directory.'],
  'checkpoint.resume': ['从保存的完整状态继续训练。', 'Continue from a saved training state.'],

  'logging.output_dir': ['保存任务日志和 TensorBoard，留空跟随默认目录。', 'Stores logs and TensorBoard data; blank uses the default directory.'],
  'logging.events_path': ['记录训练进度与损失，留空使用默认日志位置。', 'Records training progress and loss; blank uses the default log location.'],
};

export const FIELD_HELP: Record<string, Copy> = {
  'training.backbone_lr': ['主模型学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'Main model learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.text_encoder_lr': ['文本编码器学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'Text encoder learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.text_encoder_2_lr': ['CLIP-G 学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'CLIP-G learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.llm_adapter_lr': ['LLM Adapter 学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'LLM Adapter learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.self_attn_lr': ['自注意力学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'Self-attention learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.cross_attn_lr': ['交叉注意力学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'Cross-attention learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.mlp_lr': ['MLP 学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'MLP learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'training.modulation_lr': ['调制层学习率。留空沿用参数组或基础学习率，0 冻结对应参数。\n模块专用学习率优先于参数组，参数组优先于组件学习率。自动管理学习率的优化器仅允许留空或设为 0。', 'Modulation learning rate. Blank inherits group or base rates; 0 freezes matching parameters.\nModule rates override custom groups; custom groups override component rates. Optimizers that manage learning rates accept only blank or 0.'],
  'dataset.caption.weighted': ['(标签)：提高权重。\n(标签:1.2)：使用指定权重。\n[标签]：降低权重。\n可用反斜杠转义括号。作用于两个 CLIP 的序列特征，不改变池化特征；训练与采样使用同一规则。', '(tag): increase its weight.\n(tag:1.2): use an explicit weight.\n[tag]: reduce its weight.\nEscape brackets with a backslash. Applies to both CLIP sequence features, preserving pooled features. Training and previews use the same rule.'],
  'objective.noise_offset': ['为每张图的每个潜空间通道增加共享噪声，输入和训练目标同时使用。0 关闭。\n不与多分辨率噪声同时使用；输入扰动是另一项设置，只改变训练输入。', 'Adds shared noise to each latent channel per image, affecting both inputs and targets. 0 disables it.\nCannot be combined with multiresolution noise. Input perturbation is separate and changes only the input.'],
  'objective.multires_noise_iterations': ['逐层生成更低分辨率的噪声，放大叠加后归一化，用于训练输入和目标。0 关闭。\n不与噪声偏移同时使用。', 'Generates progressively lower-resolution noise, upsamples, combines and normalizes it for inputs and targets. 0 disables it.\nCannot be combined with noise offset.'],
  'objective.multires_noise_discount': ['第 i 层低分辨率噪声乘以此值的 i 次方。默认 0.3；越小，后续层的贡献越低。', 'Scales low-resolution noise level i by this value raised to i. Default 0.3; lower values reduce later contributions.'],
  'optimizer.cpu_offload': ['在 CPU 保存 FP32 参数副本和 AdamW 状态，并执行更新；训练仍在显卡上进行。增加内存占用与每步传输时间。\n支持全量微调的单卡和 DDP；不支持 FSDP、低精度更新补偿或 fused 优化器。', 'Keeps FP32 parameter copies and AdamW states on the CPU and updates them there; model computation stays on the GPU. Increases RAM use and transfer time per step.\nSupports full fine-tuning on one GPU or DDP; excludes FSDP, Kahan updates and fused optimizers.'],
  'optimizer.exclude_bias_norm_from_weight_decay': ['全量微调时，偏置及 LayerNorm、RMSNorm 等归一化层参数不做权重衰减，其他参数使用配置的衰减值。', 'During full fine-tuning, biases and normalization parameters such as LayerNorm and RMSNorm receive no weight decay. Other parameters use the configured decay.'],
  'checkpoint.metadata_title': ['模型在支持元数据的软件中显示的标题。留空使用权重文件名前缀，不改变导出文件名。', 'Display title in software that reads model metadata. Blank uses the weight file name prefix; does not rename the exported file.'],
  'checkpoint.metadata_author': ['写入模型元数据的作者或组织名称，留空不写入。', 'Author or organization stored in model metadata. Omitted when blank.'],
  'checkpoint.metadata_description': ['模型用途、内容或特点，支持多行。留空不写入。', 'Model purpose, content or characteristics; supports multiple lines. Omitted when blank.'],
  'checkpoint.metadata_license': ['模型许可证名称、条款或链接，留空不写入。', 'Model license name, terms or link. Omitted when blank.'],
  'checkpoint.metadata_merged_from': ['模型合并使用的来源模型名称，留空不写入。', 'Names of source models used in a merge. Omitted when blank.'],
  'checkpoint.metadata_tags': ['用于分类和查找模型的标签，多个用逗号分隔。留空不写入。', 'Tags for organizing and finding the model; separate multiple tags with commas. Omitted when blank.'],
  'checkpoint.metadata_usage_hint': ['推荐权重、提示词写法或出图设置，供模型使用者参考。支持多行，留空不写入。', 'Suggested strength, prompt wording or generation settings for model users. Supports multiple lines; omitted when blank.'],
  'checkpoint.metadata_trigger_phrase': ['记录使用模型时推荐的触发词，不会添加到训练标签中。留空不写入。', 'Record the recommended trigger phrase for using the model. Does not add it to training captions. Omitted when blank.'],
  'memory.vae_encode_batch_size': ['训练时一次可以同时对多少张图片进行 VAE 编码。默认保持 1 即可，过大的值会导致 VAE 编码阶段显存成倍增长，调大并不会增加训练速度。', 'How many images are VAE-encoded at once during training. Keep the default of 1; larger values multiply the memory used while encoding and do not make training faster.'],
  'memory.vae_tiling': ['将图像按 512 像素分块进行 VAE 编码和解码，相邻块重叠 128 像素，可减少显存占用，但可能增加耗时。默认关闭。', 'Encodes and decodes images in 512-pixel VAE tiles with 128-pixel overlap. This reduces VRAM use but may take longer. Off by default.'],
  'memory.cache_encode_tiled': ['仅在创建图像缓存时，对面积超过 2048×2048 像素的图片按 1024 像素分块编码，相邻块重叠 128 像素。小图沿用 VAE 分块设置，不影响预览解码。默认关闭。', 'When creating image caches, images larger than 2048×2048 pixels in area are encoded in 1024-pixel tiles with 128-pixel overlap. Smaller images follow the VAE tiling setting. Preview decoding is unchanged. Off by default.'],
  'memory.no_half_vae': ['强制 VAE 使用 FP32 编码和解码图像，能减少低精度计算引起的数值异常，但会增加显存占用，并可能降低速度。默认关闭。', 'Forces the VAE to encode and decode images in FP32. This reduces numerical issues from low-precision computation, but uses more VRAM and may be slower. Off by default.'],
  'memory.vae_attention_chunking': ['默认关闭。用于 Anima / Krea 2 在 HIP 环境下的图片 VAE，编码和解码均适用。\n开启后，仅在 VAE 没有可用融合注意力后端时，把查询按最多 2048 个一组计算，仍使用整张图的键和值，减少数学注意力的临时显存；可能增加耗时。可用的融合后端仍优先使用。\n这不是按图片区域切块的 Tiled VAE，也不改变主模型的注意力后端。', 'Off by default. Applies to image VAE encoding and decoding for Anima / Krea 2 on HIP.\nWhen enabled, and only when no fused VAE attention backend is available, queries are processed in chunks of up to 2048 while retaining keys and values for the whole image. This reduces temporary memory for math attention and may take longer. Available fused backends still take priority.\nThis is not spatial Tiled VAE and does not change the main model attention backend.'],
  // What each weight is for; the model's own hint about files follows on the next line.
  'model.dit_path': ['生成图像的主模型权重，训练针对的就是它。', 'Weights of the model that generates the images; training targets it.'],
  'model.text_encoder_path': ['把标签文字转换成主模型能理解的特征。', 'Turns caption text into features the main model understands.'],
  'model.text_encoder_2_path': ['SDXL 的第二个文本编码器，与第一个一起把标签转换成特征。', "SDXL's second text encoder; together with the first it turns captions into features."],
  'model.vae_path': ['在图片和潜空间之间转换：训练前把图片编码成潜空间，预览时把结果解码回图片。', 'Converts between images and latents: it encodes images before training and decodes previews back into images.'],
  'model.tokenizer_path': ['把标签切分成文本编码器使用的词元（token）。', 'Splits captions into the tokens the text encoder uses.'],
  'adapter.tlora_min_rank': ['T-LoRA 在噪声最大时只使用前几个秩，噪声越小可用的越多，接近干净图时用满 Rank。这里设置最少保留几个，留空为 Rank 的一半。数值越小，高噪声阶段越不容易死记训练图的构图，但能学到的也越少。', 'At the noisiest step T-LoRA uses only its first few ranks, more as the noise falls, and the whole rank near clean images. This sets how many it keeps at least; blank is half the rank. Fewer ranks copy the training images\' composition less at high noise but also learn less.'],
  'adapter.tlora_power': ['控制可用的秩随噪声下降而增加的快慢：可用的秩 = (1 − 噪声强度)^指数 × (Rank − 最小秩) + 最小秩。默认 1 为线性；大于 1 时高噪声段更久只用较少的秩，小于 1 时更早放开。', 'How fast the usable ranks grow as the noise falls: ranks = (1 − noise level)^power × (rank − minimum) + minimum. 1 (default) is linear; above 1 the noisy steps keep few ranks for longer, below 1 they open sooner.'],
  'adapter.tlora_ortho': ['开启后，各秩从互相正交的方向开始，并减去一份冻结的初始副本，所以训练开始时不改变底模输出。这种形式导出的普通 LoRA 秩是设定值的两倍，文件也相应变大。关闭则与普通 LoRA 的初始化相同，导出的秩不变。', "On, every rank starts in its own orthogonal direction and a frozen copy of that start is subtracted, so training starts from the base model's output. The exported plain LoRA then has twice the set rank and a larger file. Off, the start is that of a plain LoRA and the exported rank is unchanged."],
  'objective.ip_noise_gamma': ['给加噪后的训练输入再叠加一点额外噪声，训练目标仍使用原来的噪声，用来缓解训练和生成时输入不一致的问题。默认 0 关闭，常用 0.1 左右。', 'Adds a little extra noise to the noisy training input while the target keeps the original noise, which reduces the mismatch between training and generation. 0 (default) disables it; about 0.1 is common.'],
  'dataset.batch_size': ['每批参与一次梯度计算的图片数，等效批次 = 批大小 × 梯度累积 × 显卡数。分桶模式只把相同尺寸的图片组成一批；原生分辨率下，同一批里尺寸不同的图片会分开计算，整批算完后才合并梯度更新参数，所以等效批次不变。不足一批的尾部不会复制图片补齐。', 'Images in one gradient computation; effective batch = batch size × gradient accumulation × GPUs. Bucket mode batches only same-size images. In native resolution, differently sized images in a batch are computed separately and their gradients are combined before the update, so the effective batch is unchanged. A short final batch is not padded with repeated images.'],
  'dataset.caption.shuffle': ['TXT 只打乱未保留的标签；分类 JSON 只打乱可变分组内的标签，固定信息和自然语言不动。使用文本缓存时，从预生成的随机变体中选择。', 'Shuffles unprotected TXT tags or tags within variable JSON groups. Fixed information and natural language stay unchanged. Text caching selects from pre-generated random variants.'],
  'dataset.caption.keep_tokens': ['仅用于 TXT：前 N 个标签不参与打乱或标签丢弃。即使关闭打乱，只要启用了标签丢弃，此设置仍然有效。分类 JSON 按字段分组处理，不使用此计数。', 'For TXT captions, protects the first N tags from shuffling and tag dropout. Still applies with shuffling off when tag dropout is enabled. Structured JSON uses its fixed fields instead of this count.'],
  'sampling.enabled': ['按设定间隔生成预览图，需要至少一条提示词或提示词文件。生成预览会占用时间，不参与梯度更新。', 'Generates previews at the chosen intervals. Requires at least one prompt or a prompt file. Preview generation takes time and does not update training gradients.'],
  'validation.enabled': ['使用固定验证图片和噪声计算损失，不对验证图片反向更新。需要设置验证划分比例或单独的验证数据来源。', 'Measures loss with fixed validation images and noise, without updating weights from validation images. Set a validation split or a separate validation data source.'],
  'loop.ema': ['在 CPU 维护适配器权重的指数移动平均，额外保存 EMA 权重用于对比，会增加内存和文件占用。训练预览仍使用普通权重。', 'Maintains an exponential moving average of adapter weights on the CPU and exports an additional set of EMA weights. Uses extra memory and storage. Training previews still use the regular weights.'],
  'model.family': ['决定可用的模型文件、训练方式和默认参数。名称中的 B 表示十亿个主模型参数，不含文本编码器与 VAE；Klein 的实际规模由模型版本决定。', 'Determines the model files, training modes and defaults. B denotes billion backbone parameters, excluding text encoders and the VAE; the Klein variant determines its actual size.'],
  'dataset.sources': ['参与训练的图片目录。重复次数表示每轮使用这组图片的遍数，数值越大，这组图片在训练中的占比越高。图片没有标签文件时，可以填写“无标签时的描述”作为标签。', 'Image folders used for training. Repeats set how many times a folder is used per epoch; higher values give it a larger share. Text for uncaptioned images is used when an image has no caption file.'],
  'dataset.flip': ['训练时随机左右翻转图片，让模型看到更多变化。开启后会多缓存一份翻转后的图像编码。画面含文字或左右不对称的特征时不建议开启。', 'Randomly mirrors images during training for more variety. Caches an extra flipped encoding. Avoid it when images contain text or asymmetric features.'],
  'dataset.masked_loss': ['使用同名的 .mask.png 遮罩或图片自身的透明通道控制每个区域参与训练的程度：白色或不透明区域正常训练，黑色或完全透明的区域不参与。没有遮罩和透明像素的图片按整张训练。', 'Uses a matching .mask.png or the image alpha channel to weight each region: white or opaque areas train normally, black or fully transparent areas are ignored. Images without masks or transparent pixels train as a whole.'],
  'dataset.num_workers': ['后台读取和处理图片的进程数。0 表示在训练进程内读取，最稳定，Windows 建议保持 0。图像已缓存时读取负担较小，通常不需要增加。', 'Background processes that load images. 0 loads inside the training process and is the most stable choice on Windows. With cached images the loading work is small, so more workers rarely help.'],
  'dataset.cache_dir': ['保存可复用的图像编码和文本特征。留空使用“设置 → 存储路径”中的缓存目录；指定其他目录后会在新位置生成缓存。', 'Stores reusable image and text features. Blank uses the cache directory in Settings → Storage paths; choosing another directory creates caches there.'],
  'dataset.caption.trigger_word': ['放在标签开头的触发词，不参与打乱和丢弃；标签中已有的同名词会移到开头。训练后在提示词中写这个词即可调用学到的内容。', 'A trigger placed at the start of every caption and never shuffled or dropped; an identical existing tag moves to the front. Use it in prompts to invoke what was learned.'],
  'dataset.caption.prefix': ['加在每条标签最前面的固定文字，位于触发词之前，不参与打乱和丢弃。', 'Fixed text placed before every caption, ahead of the trigger word. It is never shuffled or dropped.'],
  'dataset.caption.suffix': ['加在每条标签末尾的固定文字，不参与打乱和丢弃。', 'Fixed text placed after every caption. It is never shuffled or dropped.'],
  'dataset.caption.separator': ['TXT 标签中分隔各个标签的字符，默认为英文逗号。打乱、丢弃和保留前几个标签都按它拆分。', 'Character separating tags in TXT captions, a comma by default. Shuffling, dropout and kept tags all split on it.'],
  'dataset.caption.caption_dropout': ['按此概率把整条标签换成空文本，让模型同时学习不看标签的生成，有助于提示词引导（CFG）。0 表示关闭，常用 0～0.1。', 'Replaces the whole caption with empty text at this rate so the model also learns unconditioned generation, which helps CFG. 0 disables it; 0–0.1 is common.'],
  'dataset.caption.wildcard': ['允许在标签中写 {红色|蓝色}，每次训练随机选择其中一项。', 'Allows {red|blue} in captions; one option is picked at random each time.'],
  'dataset.caption.cache_variants': ['使用文本缓存时，每张图预先生成多少种随机标签组合。只在打乱、标签丢弃或通配符生效时有意义；数值越大，变化越多，缓存也越大。', 'Random caption variants prepared per image when text is cached. Only useful with shuffling, tag dropout or wildcards; more variants add variety and cache size.'],
  'adapter.rules': ['按层名匹配，为匹配的层单独设置算法、Rank、Alpha、Factor 或学习率；算法选 none 可排除该层。每层只使用第一条匹配的规则，规则也能加入作用范围之外的层。写法为通配符（如 blocks.*），以 re: 开头时按正则表达式匹配。', 'Matches layers by name to set their algorithm, rank, alpha, factor or learning rate; algorithm none excludes a layer. Each layer uses the first matching rule, and a rule can add layers outside the scope. Use globs such as blocks.*, or a re: prefix for regular expressions.'],
  'adapter.dora': ['DoRA 分别学习权重的幅度和方向，默认关闭，会增加计算和显存开销。“逐层覆盖规则”中使用 LyCORIS Full 或 T-LoRA 的层不启用 DoRA。只有一个输出通道的层不使用 DoRA，按所选算法训练；继续训练时沿用原任务的设置。', 'DoRA learns weight magnitude and direction separately. It is off by default and adds compute and memory overhead. Layers using LyCORIS Full or T-LoRA in per-layer rules leave DoRA off. Layers with a single output channel train without DoRA, with the selected algorithm; resuming keeps the setting the run started with.'],
  'adapter.dora_axis': ['按输入通道：每个输入通道一个幅度，默认方向。ComfyUI、Forge 和 A1111 都能加载；LyCORIS 自带的工具不支持。\n按输出通道：每个输出通道一个幅度，LyCORIS 的默认方向。ComfyUI 和 Forge 能加载，A1111 不支持。\n继续训练时须与原权重方向一致。', 'Input: one magnitude per input channel; the default. ComfyUI, Forge and A1111 load it; LyCORIS’s own tools do not support it.\nOutput: one magnitude per output channel; the LyCORIS default. ComfyUI and Forge load it; A1111 does not support it.\nKeep the original axis when resuming.'],
  'adapter.dora_compute_mode': ['标准模式：使用 FP32 计算 DoRA。\n兼容模式：训练时考虑权重保存和融合过程中的精度变化，减少导出前后的计算差异。', 'Standard mode: computes DoRA in FP32.\nCompatibility mode: accounts for precision changes during weight saving and merging to reduce computation differences before and after export.'],
  'adapter.dora_merge_dtype': ['底模与 DoRA 权重合并时使用的计算精度。自动依据当前底模的加载设置确定，并显示检测结果。此项独立于可训练参数精度和权重保存精度。', 'The precision used to merge the base model and DoRA weights. Auto resolves it from the current base-model loading settings and displays the detected result. This is independent of trainable parameter and weight save precision.'],
  'adapter.rs_lora': ['按 Alpha ÷ √Rank 缩放更新（普通方式为 Alpha ÷ Rank），Rank 较大时训练更稳定。开启后更新幅度会变化，需要重新调整学习率或 Alpha。', 'Scales updates by alpha ÷ √rank instead of alpha ÷ rank, which is steadier at high ranks. The update size changes, so revisit the learning rate or alpha.'],
  'adapter.init': ['默认：一侧矩阵从零开始，训练开始时输出与底模一致。\n随机权重＋零值缩放：两侧都随机初始化，再用从 0 开始的可训练缩放控制输出。', 'Default starts one matrix at zero, so the output initially matches the base model.\nRandom weights + zero scale initializes both sides randomly and controls the output with a trainable scale that starts at 0.'],
  'adapter.dropout': ['训练时按此比例随机屏蔽适配器输出，减轻过拟合。0 表示关闭，常用 0～0.1。', 'Randomly masks adapter outputs at this rate to reduce overfitting. 0 disables it; 0–0.1 is common.'],
  'adapter.rank_dropout': ['训练时按此比例随机屏蔽部分秩通道，避免只依赖少数通道，可减轻过拟合。0 表示关闭。', 'Randomly masks this share of rank channels during training so the adapter does not rely on a few of them, which can reduce overfitting. 0 disables it.'],
  'adapter.module_dropout': ['训练时按此概率跳过整个适配器模块、直接使用底模输出，可减轻过拟合。0 表示关闭；多卡显存分片不支持。', 'Skips whole adapter modules at this rate and uses the base output instead, which can reduce overfitting. 0 disables it; memory sharding does not support it.'],
  'adapter.layer_types': ['决定训练层范围内哪些类型的层添加适配器。\n只训练线性层：注意力、前馈等线性层。\n线性层和卷积层：另加 ResNet 模块和上下采样层，与 kohya LoCon 相同；“全部层”还包括输入、输出卷积。参数更多，显存和训练时间也会增加。', 'Which kinds of layers in the scope receive adapters.\nLinear only: attention, feed-forward and other linear layers.\nLinear + convolution: also the ResNet and resampling blocks, as kohya LoCon does; All layers also includes the input and output convolutions. This adds parameters, memory and training time.'],
  'adapter.conv_rank': ['3×3 等大于 1×1 的卷积层使用的 Rank，与 kohya、LyCORIS 的 conv_dim 相同。留空时与 Rank 相同；卷积层参数较多，常设得比 Rank 小，例如 Rank 32、卷积层 Rank 8～16。1×1 卷积按 Rank 训练。', 'Rank of convolutions larger than 1×1, the same as kohya and LyCORIS conv_dim. Blank follows Rank. Convolutions hold many parameters, so this is often lower than the rank, e.g. 8–16 with a rank of 32. 1×1 convolutions use the rank.'],
  'adapter.conv_alpha': ['这些卷积层的更新缩放系数，与 kohya、LyCORIS 的 conv_alpha 相同，按 卷积层 Alpha ÷ 卷积层 Rank 缩放。留空时与 Alpha 相同。', 'Update scale of those convolutions, the same as kohya and LyCORIS conv_alpha: updates scale by convolution alpha ÷ convolution rank. Blank follows Alpha.'],
  'adapter.mode': ['分开计算：底模和适配器各自计算后相加，不改变底模权重精度。\n合并计算：先把适配器合并进权重再计算，DoRA 需要这种方式。\n自动：能分开计算时分开计算，否则合并。', 'Separate computes the base model and the adapter independently and adds them, keeping base precision.\nMerged folds the adapter into the weight first, which DoRA requires.\nAutomatic uses separate computation when possible.'],
  'adapter.param_dtype': ['适配器可训练参数的存储精度，默认 FP32。\nBF16 节省显存，但较小的更新可能被舍入。\n此设置不决定导出文件或外部工具融合权重的精度。', 'Storage precision of trainable adapter parameters; FP32 by default.\nBF16 saves memory but small updates may be rounded away.\nThis does not set export precision or the precision external tools use to merge weights.'],
  'adapter.lr_scale': ['按参数类别设置学习率倍率。例如 LoRA+ 常把 up 设为 16，LoKr 可单独调整 w1。不熟悉时留空。', 'Learning-rate multipliers by parameter type. LoRA+ commonly sets up to 16, and LoKr can adjust w1 separately. Leave empty if unsure.'],
  'checkpoint.save_dtype': ['导出权重及 DoRA 幅度的精度，默认 BF16；缩放用的 alpha 标量保留 FP32。不会改变训练参数、完整恢复状态或外部工具的融合精度。\nFP32 文件更大，导出舍入更少。', 'Precision of exported weights and DoRA magnitudes, BF16 by default; numeric alpha scalars stay FP32 to preserve scaling. This does not change training parameters, full recovery states, or the merging precision of external tools.\nFP32 exports are larger with less rounding.'],
  'checkpoint.output_dir': ['导出权重的保存根目录，任务按项目、版本和任务 ID 分开保存。未单独指定的恢复点和日志也保存在这里。', 'Root for exported weights, organized by project, version and job ID. Recovery points and logs also go here unless configured separately.'],
  'checkpoint.state_dir': ['保存续训所需的权重、优化器、步数与随机状态。留空使用“设置 → 存储路径”中的恢复点目录；该项也未设置时保存在版本目录的 jobs/<任务>/resume。自定义目录下按项目、版本和任务分开存放。', 'Stores weights, optimizer, step and random state for resuming. Blank uses the recovery directory in Settings → Storage paths, or jobs/<job>/resume in the version folder if unset. Custom roots are organized by project, version and job.'],
  'sampling.noise': ['ComfyUI：使用对应的导出适配器融合规则，初始噪声在 CPU 上生成。\nA1111 WebUI：保留训练器原有融合方式，逐张按种子生成噪声；NVIDIA / 海光显卡使用显卡，CPU / Apple 芯片使用 CPU。\nEuler a、ER-SDE 追加噪声也使用所选规则。仅影响采样，不改变训练计算。', 'ComfyUI: uses the corresponding exported-adapter merging rules and draws initial noise on the CPU.\nA1111 WebUI: keeps the trainer’s original merging and draws per-image seeded noise on NVIDIA / Hygon GPUs, or on the CPU for CPU / Apple devices.\nEuler a and ER-SDE also follow the selected noise rules. Affects sampling, not training.'],
  'sampling.adapter_merge_dtype': ['ComfyUI 模式下融合导出适配器的计算精度。\n自动：跟随底模实际浮点精度，对应 ComfyUI 的动态加载方式。\nBF16 / FP16 / FP32：按外部加载方式指定融合精度。只控制适配器融合，不改变推理精度或训练计算。', 'The precision used to merge exported adapters in ComfyUI mode.\nAuto: follows the base model’s actual floating-point precision, matching ComfyUI dynamic loading.\nBF16 / FP16 / FP32: select the merge precision used by your external loader. This does not change inference precision or training computation.'],
  'sampling.output_dir': ['保存训练预览图。留空使用“设置 → 存储路径”中的采样图目录；该项也未设置时保存在项目版本的 samples 目录。自定义目录下按项目、版本和任务分开存放。', 'Stores training previews. Blank uses the sample directory in Settings → Storage paths, or the project version’s samples folder if unset. Custom roots are organized by project, version and job.'],
  'checkpoint.save_on_finish': ['训练结束时导出最终权重。关闭后只保留按步或按轮导出的文件。', 'Exports the final weights when training ends. When off, only step or epoch exports are kept.'],
  'checkpoint.keep_last_n': ['只保留最近 N 组按步导出的权重，更早的自动删除；按轮导出和最终权重不受影响。留空保留全部。', 'Keeps only the latest N step exports and deletes older ones; epoch exports and final weights are unaffected. Blank keeps all.'],
  'validation.sources': ['只用于验证、不参与训练的图片目录。设置后可以不从训练图中划分验证集。', 'Image folders used only for validation, never for training. With these set, no training images need to be held out.'],
  'validation.every_steps': ['每隔多少次优化更新计算一次验证损失。留空不按步验证。', 'Computes validation loss every N optimizer updates. Blank disables step-based validation.'],
  'validation.every_epochs': ['每隔多少轮计算一次验证损失。留空不按轮验证。', 'Computes validation loss every N epochs. Blank disables epoch-based validation.'],
  'validation.seed': ['验证加噪使用的随机种子。保持不变，不同时间点的验证损失才能直接比较。', 'Random seed for validation noise. Keep it fixed so validation losses stay comparable over time.'],
  'logging.output_dir': ['保存控制台日志、训练事件与 TensorBoard 数据。留空使用“设置 → 存储路径”中的日志目录；该项也未设置时保存在版本目录的 jobs/<任务>。自定义目录下按项目、版本和任务分开存放。', 'Stores console logs, training events and TensorBoard data. Blank uses the log directory in Settings → Storage paths, or jobs/<job> in the version folder if unset. Custom roots are organized by project, version and job.'],
  'logging.events_path': ['记录训练进度、损失等事件的文件，默认名为 events.jsonl。设置了日志保存目录时使用该目录；否则使用此文件的父目录作为日志根目录。', 'Records training progress, losses and other events, named events.jsonl by default. Uses the configured log directory, or this file’s parent as the log root.'],
};

const MODEL_PATH_HINTS: Record<string, Record<string, Copy>> = {
  anima: {
    dit_path: ['Anima 主模型权重文件。', 'Anima main model weights.'],
    text_encoder_path: ['Qwen3-0.6B 文本编码器。', 'Qwen3-0.6B text encoder.'],
    vae_path: ['Qwen-Image VAE 文件。', 'Qwen-Image VAE file.'],
    tokenizer_path: ['留空使用内置分词器。', 'Blank uses the built-in tokenizer.'],
  },
  flux2: {
    dit_path: ['Klein 基础版完整目录或单文件。', 'Klein base folder or single file.'],
    text_encoder_path: ['完整模型目录可留空。', 'Optional with a full model folder.'],
    vae_path: ['完整模型目录可留空。', 'Optional with a full model folder.'],
    tokenizer_path: ['模型目录内含分词器时可留空。', 'Optional when the model folder includes one.'],
  },
  krea2: {
    dit_path: ['Krea 2 Raw 主模型，BF16 或 FP8 文件。', 'Krea 2 Raw main model, BF16 or FP8.'],
    text_encoder_path: ['Qwen3-VL-4B 文本编码器。', 'Qwen3-VL-4B text encoder.'],
    vae_path: ['Qwen-Image VAE，与 Anima 通用。', 'Qwen-Image VAE, shared with Anima.'],
    tokenizer_path: ['留空使用模型自带的分词器。', 'Blank uses the bundled tokenizer.'],
  },
  sdxl: {
    dit_path: ['完整 SDXL 模型文件或 Diffusers 目录。', 'Full SDXL checkpoint or Diffusers folder.'],
    text_encoder_path: ['留空使用模型内含的 CLIP-L。', 'Blank uses the bundled CLIP-L.'],
    text_encoder_2_path: ['留空使用模型内含的 CLIP-G。', 'Blank uses the bundled CLIP-G.'],
    vae_path: ['留空使用模型内含的 VAE。', 'Blank uses the bundled VAE.'],
    tokenizer_path: ['可选，留空自动读取模型目录。', 'Optional; blank reads the model folder.'],
  },
};

const GENERIC_MODEL_PATH_HINTS: Record<string, Copy> = {
  dit_path: ['主模型权重，可从已登记模型中选择。', 'Main model weights; pick a registered model or browse.'],
  text_encoder_path: ['把标签文字转换为特征的模型。', 'Model that turns captions into features.'],
  text_encoder_2_path: ['第二个文本编码器。', 'Second text encoder.'],
  vae_path: ['在图片与潜空间之间转换的模型。', 'Converts between images and latents.'],
  tokenizer_path: ['可选，留空自动选择分词器。', 'Optional; blank picks the tokenizer automatically.'],
};

/** Presets may leave model files empty; applying one then keeps the configuration's files. */
export function modelPathHint(family: string | undefined, field: string, english: boolean, preset = false) {
  if (preset) return english ? 'Blank keeps the training configuration’s model.' : '留空时沿用训练配置中的模型。';
  const copy = (family && MODEL_PATH_HINTS[family]?.[field]) || GENERIC_MODEL_PATH_HINTS[field];
  return copy?.[english ? 1 : 0];
}
